//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string Gender { get; set; }
        public string Designation { get; set; }
        public string Salary { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MoNumber { get; set; }
        public string DeptName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> AId { get; set; }
        public string Hobby { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
